/**
 * @file vfs.h
 * @brief Unified virtual filesystem — O(log n) lookup over sorted entry arrays.
 *
 * Hull embeds app and stdlib files (`templates/`, `static/`, `migrations/`,
 * `compute/`, `shaders/`, Lua/JS modules) as a single sorted `HlEntry` array
 * generated by the build at link time. The VFS wraps that array with
 * binary-search find, prefix query, and filesystem-path construction so
 * dev mode (root_dir → disk) and build mode (embedded entries) use the
 * same call sites.
 *
 * Two instances exist on every #HlRuntime:
 *   - `platform_vfs` — stdlib (always embedded, `root_dir = NULL`).
 *   - `app_vfs` — app files (embedded in built binaries; filesystem
 *     fallback via `root_dir` in `hull dev`).
 *
 * @par Sort invariant:
 *   Entries must be sorted by name in C `strcmp` order. The Makefile uses
 *   `LC_ALL=C sort` to guarantee this; @ref hl_vfs_init debug-asserts it.
 *
 * @par Naming convention (disambiguates types in the single array):
 *   - `./<name>` — Lua/JS app modules
 *   - `templates/<name>` — HTML templates
 *   - `static/<path>` — static assets
 *   - `migrations/<name>.sql` — SQL migrations
 *   - `compute/<name>.wasm` / `.aot.<arch>` — WASM plugins
 *   - `shaders/<name>.wgsl` — WGSL compute shaders
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#ifndef HL_VFS_H
#define HL_VFS_H

#include "hull/entry.h"
#include <stddef.h>

typedef struct HlVfs {
    const HlEntry *entries;   /* sorted by name, sentinel-terminated */
    size_t         count;     /* number of entries (excl sentinel) */
    const char    *root_dir;  /* filesystem root for dev mode, or NULL */
} HlVfs;

/**
 * @brief Initialize a VFS over a sentinel-terminated entry array.
 *
 * Counts entries, stores the borrowed `root_dir` pointer, and debug-asserts
 * sort order. The entry array must outlive the VFS (typically static storage
 * from generated `app_registry.c` / `stdlib_registry.c`).
 *
 * @param vfs      Storage to initialize.
 * @param entries  Sentinel-terminated array (last entry has `name == NULL`).
 * @param root_dir Filesystem root for dev-mode fallback, or NULL.
 */
void hl_vfs_init(HlVfs *vfs, const HlEntry *entries, const char *root_dir);

/**
 * @brief Exact lookup by name (binary search, O(log n)).
 * @return Pointer to the matching entry, or NULL if not found.
 */
const HlEntry *hl_vfs_find(const HlVfs *vfs, const char *name);

/**
 * @brief Prefix query (binary search, O(log n)).
 *
 * Finds the first entry whose name begins with `prefix` and returns the
 * contiguous match count. Used by callers that need to iterate every file
 * under a directory (e.g. `migrations/`).
 *
 * @param[in]  vfs    VFS to query.
 * @param[in]  prefix Name prefix.
 * @param[out] first  Receives the first matching entry, or NULL if none.
 * @return Number of contiguous matching entries (0 if none).
 */
size_t hl_vfs_prefix(const HlVfs *vfs, const char *prefix,
                     const HlEntry **first);

/**
 * @brief Prefix existence check.
 * @return 1 if any entry name starts with `prefix`, 0 otherwise.
 */
int hl_vfs_has_prefix(const HlVfs *vfs, const char *prefix);

/**
 * @brief Build a filesystem path: `root_dir/name` → `buf`.
 *
 * @return Number of bytes written (excluding the NUL terminator), or -1 if
 *   `root_dir` is NULL, the buffer is too small, or any argument is invalid.
 */
int hl_vfs_path(const HlVfs *vfs, const char *name,
                char *buf, size_t buf_size);

#endif /* HL_VFS_H */
