/*
 * frontend/js_session.c - the restricted QuickJS tooling runtime.
 * See include/hull/frontend/js_session.h + docs/javascript_source_frontend_design.md.
 *
 * The session context NEVER enables the QuickJS eval hook (JS_AddIntrinsicEval), so every
 * dynamic-compile path (eval, Function, and the prototype-reachable constructors) throws
 * "eval is not supported". The trusted cli-js bundle is compiled to bytecode ONCE in a
 * throwaway eval-enabled context at create time and loaded into the session via
 * JS_ReadObject, which needs no eval hook.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
#include "hull/frontend/js_session.h"

#include "quickjs.h"
#include "hull/entry.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Real allocator usable-size + per-block overhead, so the session's running total mirrors
 * QuickJS's own malloc_size accounting byte-for-byte (see js_def_malloc in quickjs.c). */
#if defined(__APPLE__)
#  include <malloc/malloc.h>
#  define HL_JS_USABLE_SIZE(p) malloc_size(p)
#  define HL_JS_MALLOC_OVERHEAD 0
#elif defined(__GLIBC__) || defined(__linux__) || defined(__COSMOPOLITAN__)
#  include <malloc.h>
   /* glibc malloc_usable_size takes void*; launder the const through uintptr_t (read-only
    * size accounting, never a write) so -Werror=cast-qual accepts it. macOS malloc_size above
    * already takes const void*, so only this path needs the launder. */
#  define HL_JS_USABLE_SIZE(p) malloc_usable_size((void *)(uintptr_t)(p))
#  define HL_JS_MALLOC_OVERHEAD 8
#else
#  define HL_JS_USABLE_SIZE(p) 0   /* accounting is approximate; the limit still enforces */
#  define HL_JS_MALLOC_OVERHEAD 8
#endif

/* The bundled cli-js tooling registry (generated by the Makefile from stdlib/cli/js).
 * Loaded ONLY into this tooling runtime -- never the application JS runtime. A
 * name-NULL sentinel terminates the array. */
extern const HlEntry hl_stdlib_js_cli_entries[];

/* One precompiled tooling module: its registry name (borrowed, stable) + owned bytecode. */
typedef struct {
    const char *name;
    uint8_t    *bc;
    size_t      bc_len;
} HlJsBcModule;

struct HlJsSession {
    JSRuntime        *rt;
    JSContext        *ctx;
    HlJsSessionLimits limits;
    int64_t           instr_count;     /* interrupt polls seen in the current invocation */
    int64_t           instr_limit;     /* == limits.max_instructions (0 = unlimited) */
    /* Authoritative, NON-FORGEABLE resource markers. A genuine breach is host-imposed (the
     * allocator refused, the interrupt fired) and cannot be simulated by JS: a script can throw
     * an error whose .name is "InternalError" and whose .message is "out of memory", but it
     * cannot make the allocator return NULL or drive the machine stack past the guard. So these
     * flags -- not the exception's name or message -- decide js.limit.heap / .stack. */
    size_t            heap_limit;      /* == limits.max_heap_bytes (0 = unlimited) */
    int               oom_hit;         /* the self-enforcing allocator refused an allocation */
    uintptr_t         stack_base;      /* machine stack pointer recorded at invocation entry */
    size_t            stack_limit;     /* == limits.max_stack_bytes (0 = unlimited) */
    int               stack_hit;       /* the interrupt stack guard tripped (uncatchable) */
    char              entry_name[128]; /* the loaded __hull_frontend entry, or "" */
    HlJsBcModule     *mods;            /* precompiled bytecode, one per cli-js entry */
    size_t            mod_count;
};

/* Current machine stack depth relative to the invocation base (the stack grows down). Uses the
 * frame address, not a local's address, so there is no -Wreturn-stack-address hazard; only the
 * DIFFERENCE from stack_base matters and every call site measures alike. */
static uintptr_t stack_ptr_now(void) { return (uintptr_t)__builtin_frame_address(0); }

/* ── self-enforcing allocator: authoritative heap AND stack markers ─────────
 * QuickJS's own JS_SetMemoryLimit / JS_SetMaxStackSize enforce INTERNALLY and leave no queryable
 * post-hoc signal. The session enforces HERE instead and records the markers fail_from_exception
 * reads, so classification is host-owned and non-forgeable:
 *   heap  -- malloc_size (QuickJS's running total) + the request vs the limit -> oom_hit.
 *   stack -- the parser allocates an AST node at EVERY recursion level, so the allocator is a
 *            per-level probe of the real machine stack: depth past the limit -> stack_hit. This
 *            is far finer than the periodic interrupt and precise for small limits. It refuses
 *            the allocation (returns NULL) so execution unwinds at once; the classifier checks
 *            stack_hit before oom_hit, so the refusal reports js.limit.stack, not heap. */
static int alloc_stack_breached(HlJsSession *s)
{
    if (!s || !s->stack_limit || !s->stack_base) return 0;
    uintptr_t sp = stack_ptr_now();
    if (s->stack_base > sp && (s->stack_base - sp) > s->stack_limit) { s->stack_hit = 1; return 1; }
    return 0;
}
static void *hl_js_malloc(JSMallocState *st, size_t size)
{
    HlJsSession *s = (HlJsSession *)st->opaque;
    if (alloc_stack_breached(s)) return NULL;
    if (s && s->heap_limit && st->malloc_size + size > s->heap_limit) { s->oom_hit = 1; return NULL; }
    void *ptr = malloc(size);
    if (!ptr) { if (s) s->oom_hit = 1; return NULL; }
    st->malloc_count++;
    st->malloc_size += (size_t)HL_JS_USABLE_SIZE(ptr) + HL_JS_MALLOC_OVERHEAD;
    return ptr;
}
static void hl_js_free(JSMallocState *st, void *ptr)
{
    if (!ptr) return;
    st->malloc_count--;
    st->malloc_size -= (size_t)HL_JS_USABLE_SIZE(ptr) + HL_JS_MALLOC_OVERHEAD;
    free(ptr);
}
static void *hl_js_realloc(JSMallocState *st, void *ptr, size_t size)
{
    HlJsSession *s = (HlJsSession *)st->opaque;
    if (alloc_stack_breached(s)) return NULL;
    if (!ptr) { if (size == 0) return NULL; return hl_js_malloc(st, size); }
    size_t old = (size_t)HL_JS_USABLE_SIZE(ptr);
    if (size == 0) { st->malloc_count--; st->malloc_size -= old + HL_JS_MALLOC_OVERHEAD; free(ptr); return NULL; }
    /* malloc_size includes this block's usable size, so malloc_size + size - old never
     * underflows -- it mirrors js_def_realloc's limit check exactly. */
    if (s && s->heap_limit && st->malloc_size + size - old > s->heap_limit) { s->oom_hit = 1; return NULL; }
    void *np = realloc(ptr, size);
    if (!np) { if (s) s->oom_hit = 1; return NULL; }
    st->malloc_size += (size_t)HL_JS_USABLE_SIZE(np) - old;
    return np;
}
static size_t hl_js_usable_size(const void *ptr) { return (size_t)HL_JS_USABLE_SIZE(ptr); }
static const JSMallocFunctions HL_JS_MALLOC_FUNCS = {
    hl_js_malloc, hl_js_free, hl_js_realloc, hl_js_usable_size,
};

/* ── interrupt handler: authoritative instruction marker ────────────────────
 * Fires periodically (every JS_INTERRUPT_COUNTER_INIT ops). Returning non-zero raises the
 * UNCATCHABLE "interrupted" error, so an exhausted instruction budget bypasses the frontend's
 * try/catch entirely and reaches the host classifier -- authoritative and non-forgeable. */
static int session_interrupt(JSRuntime *rt, void *opaque)
{
    (void)rt;
    HlJsSession *s = (HlJsSession *)opaque;
    s->instr_count++;
    return (s->instr_limit > 0 && s->instr_count > s->instr_limit) ? 1 : 0;
}

/* ── bytecode module map ────────────────────────────────────────────────── */
static const HlJsBcModule *find_module(const HlJsSession *s, const char *name)
{
    for (size_t i = 0; i < s->mod_count; i++)
        if (strcmp(s->mods[i].name, name) == 0) return &s->mods[i];
    return NULL;
}

/* Tooling-only module loader: the SESSION resolves an import by deserializing the
 * module's precompiled bytecode (no eval hook, no filesystem, no app modules). */
static char *session_module_normalize(JSContext *ctx, const char *base_name,
                                      const char *name, void *opaque)
{
    (void)base_name; (void)opaque;
    /* The bundle uses ONLY absolute `hull:*` module names -- identity normalization. */
    return js_strdup(ctx, name);
}

static JSModuleDef *session_module_loader(JSContext *ctx, const char *module_name, void *opaque)
{
    HlJsSession *s = (HlJsSession *)opaque;
    const HlJsBcModule *m = find_module(s, module_name);
    if (!m) {
        JS_ThrowReferenceError(ctx, "tooling module not found: %s", module_name);
        return NULL;
    }
    JSValue v = JS_ReadObject(ctx, m->bc, m->bc_len, JS_READ_OBJ_BYTECODE);
    if (JS_IsException(v)) return NULL;   /* the pending exception is the read failure */
    JSModuleDef *md = (JSModuleDef *)JS_VALUE_GET_PTR(v);
    JS_FreeValue(ctx, v);                 /* the module stays owned by ctx's module list */
    return md;
}

/* ── diagnostics (structured indeterminate result, never a raw exception) ── */
static char *json_escape_dup(const char *s)
{
    /* Minimal JSON string-escaper for a diagnostic message (bounded). */
    size_t n = s ? strlen(s) : 0;
    /* worst case per input byte is a 6-char \uXXXX escape, + the NUL terminator */
    size_t cap = n * 6 + 1;
    char *out = malloc(cap);
    if (!out) return NULL;
    char *p = out;
    char *end = out + cap;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '"' || c == '\\') { *p++ = '\\'; *p++ = (char)c; }
        else if (c == '\n') { *p++ = '\\'; *p++ = 'n'; }
        else if (c == '\r') { *p++ = '\\'; *p++ = 'r'; }
        else if (c == '\t') { *p++ = '\\'; *p++ = 't'; }
        else if (c < 0x20) { p += snprintf(p, (size_t)(end - p), "\\u%04x", c); }
        else { *p++ = (char)c; }
    }
    *p = '\0';
    return out;
}

static int fail_indeterminate(char **out_json, size_t *out_len, const char *code, const char *msg)
{
    char *emsg = json_escape_dup(msg ? msg : "");
    const char *safe = emsg ? emsg : "";
    size_t cap = strlen(code) + strlen(safe) + 128;
    char *j = malloc(cap);
    if (j) {
        int n = snprintf(j, cap,
            "{\"status\":\"indeterminate\",\"diagnostics\":"
            "[{\"severity\":\"error\",\"code\":\"%s\",\"message\":\"%s\"}]}",
            code, safe);
        /* Match the success path: hand ownership to the caller, else free (no leak). */
        if (out_json) *out_json = j; else free(j);
        if (out_len) *out_len = (n > 0) ? (size_t)n : 0;
    } else {
        if (out_json) *out_json = NULL;
        if (out_len) *out_len = 0;
    }
    free(emsg);
    return -1;
}

/* Convert an arbitrary JSValue to a best-effort heap C string. If JS_ToCString itself fails
 * (typically OOM while stringifying) it returns NULL AND raises a SECONDARY pending
 * exception; this helper clears that exception so it can't contaminate the next invocation
 * on a reused session. Returns a malloc'd string (caller frees), or NULL only on strdup OOM.
 * Shared by the pending-exception path and the rejected-promise-value path. */
static char *jsvalue_to_message(JSContext *ctx, JSValueConst val, const char *fallback)
{
    const char *cs = JS_ToCString(ctx, val);
    if (cs) {
        char *out = strdup(cs);
        JS_FreeCString(ctx, cs);
        return out;
    }
    JS_FreeValue(ctx, JS_GetException(ctx));   /* clear the secondary conversion exception */
    return strdup(fallback);
}

/* Pull the pending JS exception into a heap C string (best-effort). */
static char *take_exception_message(JSContext *ctx)
{
    JSValue exc = JS_GetException(ctx);
    char *out = jsvalue_to_message(ctx, exc, "unknown tooling exception");
    JS_FreeValue(ctx, exc);
    return out;
}

/* Consume the pending QuickJS exception and fail the invocation with the correctly
 * classified code. Used at EVERY phase (options parse, argument construction, module-job
 * draining, JS_Call, JS_JSONStringify, JS_ToCStringLen) so a resource breach is reported
 * as the same js.limit.* code regardless of which phase tripped it.
 *
 * Classification is by AUTHORITATIVE HOST STATE, never the exception's name or message: the
 * stack guard fired (stack_hit), the instruction budget was exhausted, or the self-enforcing
 * allocator refused (oom_hit). These are host-imposed and cannot be forged by a script that
 * merely names an error "InternalError" or writes "out of memory" into a .message -- such a
 * script's throw is an ordinary CATCHABLE exception the frontend contains as js.internal, so
 * it never reaches this classifier at all. Only a genuine host breach lands here uncaught. */
static int fail_from_exception(HlJsSession *s, JSContext *ctx,
                               char **out_json, size_t *out_len, const char *fallback)
{
    char *msg = take_exception_message(ctx);   /* reads + clears the pending exception */
    const char *code;
    if (s->stack_hit)                                              code = "js.limit.stack";
    else if (s->instr_limit > 0 && s->instr_count > s->instr_limit) code = "js.limit.instructions";
    else if (s->oom_hit)                                           code = "js.limit.heap";
    else                                                           code = fallback;
    int rc = fail_indeterminate(out_json, out_len, code, msg);
    free(msg);
    return rc;
}

/* ── bundle precompile (throwaway eval-enabled context) ─────────────────── */
/* The compiler context needs a module loader so a module's `import`s resolve while it is
 * COMPILE_ONLY-compiled: QuickJS resolves import specifiers against the loader on demand
 * (recursively compiling dependencies from source), so the bundle compiles regardless of the
 * (alphabetical) registry order -- a module may import a sibling that sorts after it. */
static char *precompile_module_normalize(JSContext *ctx, const char *base_name,
                                         const char *name, void *opaque)
{
    (void)base_name; (void)opaque;
    return js_strdup(ctx, name);      /* absolute `hull:*` specifiers -- identity */
}

/* COMPILE_ONLY-eval a module's embedded source. QuickJS's tokenizer reads ONE byte past the
 * given length expecting a NUL sentinel; the xxd-embedded arrays are exactly `len` bytes with
 * NO terminator, so copy into a NUL-terminated buffer first -- otherwise the parser reads the
 * adjacent .rodata symbol (undefined; manifests as a bogus "unexpected character" at EOF). */
static JSValue eval_module_compile_only(JSContext *ctx, const char *name,
                                        const unsigned char *data, unsigned int len)
{
    char *buf = malloc((size_t)len + 1);
    if (!buf) return JS_ThrowOutOfMemory(ctx);
    memcpy(buf, data, len);
    buf[len] = '\0';
    JSValue f = JS_Eval(ctx, buf, len, name, JS_EVAL_TYPE_MODULE | JS_EVAL_FLAG_COMPILE_ONLY);
    free(buf);
    return f;
}

static JSModuleDef *precompile_module_loader(JSContext *ctx, const char *module_name, void *opaque)
{
    (void)opaque;
    for (const HlEntry *e = hl_stdlib_js_cli_entries; e->name; e++) {
        if (strcmp(e->name, module_name) == 0) {
            JSValue f = eval_module_compile_only(ctx, module_name, e->data, e->len);
            if (JS_IsException(f)) return NULL;   /* pending exception is the syntax error */
            JSModuleDef *md = (JSModuleDef *)JS_VALUE_GET_PTR(f);
            JS_FreeValue(ctx, f);
            return md;
        }
    }
    JS_ThrowReferenceError(ctx, "tooling module not found: %s", module_name);
    return NULL;
}

/* Compile every cli-js tooling module to bytecode so the session can load them WITHOUT
 * enabling its own eval hook. Runs in a separate runtime/context that IS eval-enabled but
 * only ever sees the trusted, embedded bundle. Returns 0 on success, -1 on any failure
 * (a bundled tool that fails to compile is a build defect). */
static int precompile_bundle(HlJsSession *s)
{
    size_t n = 0;
    while (hl_stdlib_js_cli_entries[n].name) n++;
    s->mods = calloc(n ? n : 1, sizeof(*s->mods));
    if (!s->mods) return -1;
    s->mod_count = 0;

    /* The compiler context uses generous limits, decoupled from the (possibly tiny,
     * test-chosen) session limits, so precompiling the trusted bundle never trips them. The
     * stack is set above the session default because precompile runs from a deep C stack
     * (create <- caller) and COMPILE_ONLY-parses the whole bundle recursively; a bounded but
     * roomy 4 MiB is safe on the main / tool-VM thread. */
    JSRuntime *crt = JS_NewRuntime();
    if (!crt) return -1;
    HlJsSessionLimits def = HL_JS_SESSION_LIMITS_DEFAULT;
    JS_SetMemoryLimit(crt, def.max_heap_bytes);
    JS_SetMaxStackSize(crt, (size_t)4 * 1024 * 1024);
    JSContext *cctx = JS_NewContextRaw(crt);
    if (!cctx) { JS_FreeRuntime(crt); return -1; }
    JS_AddIntrinsicBaseObjects(cctx);
    JS_AddIntrinsicEval(cctx);            /* needed to COMPILE source -> bytecode */
    JS_AddIntrinsicRegExpCompiler(cctx);  /* module source may carry regex literals */
    JS_AddIntrinsicRegExp(cctx);
    /* Resolve inter-module imports from the registry on demand (order-independent). */
    JS_SetModuleLoaderFunc(crt, precompile_module_normalize, precompile_module_loader, NULL);

    int rc = 0;
    for (const HlEntry *e = hl_stdlib_js_cli_entries; e->name; e++) {
        JSValue f = eval_module_compile_only(cctx, e->name, e->data, e->len);
        if (JS_IsException(f)) {
            JS_FreeValue(cctx, JS_GetException(cctx));
            JS_FreeValue(cctx, f);
            rc = -1; break;
        }
        size_t out_len = 0;
        uint8_t *bc = JS_WriteObject(cctx, &out_len, f, JS_WRITE_OBJ_BYTECODE);
        JS_FreeValue(cctx, f);
        if (!bc || out_len == 0) { if (bc) js_free(cctx, bc); rc = -1; break; }
        uint8_t *copy = malloc(out_len);
        if (!copy) { js_free(cctx, bc); rc = -1; break; }
        memcpy(copy, bc, out_len);
        js_free(cctx, bc);
        s->mods[s->mod_count].name   = e->name;   /* borrowed from the static registry */
        s->mods[s->mod_count].bc     = copy;
        s->mods[s->mod_count].bc_len = out_len;
        s->mod_count++;
    }

    JS_FreeContext(cctx);
    JS_FreeRuntime(crt);
    return rc;
}

/* ── lifecycle ──────────────────────────────────────────────────────────── */
HlJsSession *hl_js_session_create(const HlJsSessionLimits *limits)
{
    HlJsSession *s = calloc(1, sizeof(*s));
    if (!s) return NULL;
    HlJsSessionLimits def = HL_JS_SESSION_LIMITS_DEFAULT;
    s->limits = limits ? *limits : def;
    s->instr_limit = s->limits.max_instructions;
    s->entry_name[0] = '\0';

    if (precompile_bundle(s) != 0) { hl_js_session_destroy(s); return NULL; }

    /* Runtime with the self-enforcing allocator (opaque = s) so the heap limit is host-owned.
     * Do NOT JS_SetMemoryLimit: QuickJS's own limit check refuses allocations internally and
     * leaves no queryable marker; the allocator records oom_hit instead. heap_limit is left 0
     * during setup so context + intrinsic construction is never starved; it is armed AFTER
     * setup and re-armed per invocation. */
    s->rt = JS_NewRuntime2(&HL_JS_MALLOC_FUNCS, s);
    if (!s->rt) { hl_js_session_destroy(s); return NULL; }
    s->stack_limit = s->limits.max_stack_bytes;
    /* The allocator's per-level stack probe (at stack_limit) is the authoritative marker for the
     * allocating recursion the parser does; QuickJS's own check sits a small margin ABOVE it as
     * a hard backstop for any non-allocating recursion, so the allocator gets the first shot. */
    JS_SetMaxStackSize(s->rt, s->stack_limit ? s->stack_limit + (size_t)512 * 1024 : 0);
    JS_SetInterruptHandler(s->rt, session_interrupt, s);
    JS_SetModuleLoaderFunc(s->rt, session_module_normalize, session_module_loader, s);

    s->ctx = JS_NewContextRaw(s->rt);
    if (!s->ctx) { hl_js_session_destroy(s); return NULL; }

    /* Only what the PARSER needs. Crucially NOT JS_AddIntrinsicEval: the session's eval hook
     * stays NULL, so eval / Function / constructor-reachable dynamic compilation all throw
     * "eval is not supported". The trusted bundle loads from bytecode instead. */
    JS_AddIntrinsicBaseObjects(s->ctx);
    JS_AddIntrinsicStringNormalize(s->ctx);
    JS_AddIntrinsicRegExpCompiler(s->ctx);   /* regex compilation (not JS eval) */
    JS_AddIntrinsicRegExp(s->ctx);
    JS_AddIntrinsicJSON(s->ctx);
    JS_AddIntrinsicMapSet(s->ctx);
    JS_AddIntrinsicTypedArrays(s->ctx);
    JS_AddIntrinsicPromise(s->ctx);          /* module evaluation returns a promise */

    /* Defense in depth: delete the global eval / Function bindings too. Reaching them via a
     * prototype still lands on the disabled eval hook, but removing the obvious names keeps
     * the surface clean and self-documenting. */
    JSValue g = JS_GetGlobalObject(s->ctx);
    JSAtom a_eval = JS_NewAtom(s->ctx, "eval");
    JS_DeleteProperty(s->ctx, g, a_eval, 0);
    JS_FreeAtom(s->ctx, a_eval);
    JSAtom a_fn = JS_NewAtom(s->ctx, "Function");
    JS_DeleteProperty(s->ctx, g, a_fn, 0);
    JS_FreeAtom(s->ctx, a_fn);
    JS_FreeValue(s->ctx, g);

    /* Arm the heap limit only now that context + intrinsics are built, so setup is never
     * starved by a small configured limit. Per-invocation state is (re)armed in analyze. */
    s->heap_limit = s->limits.max_heap_bytes;

    return s;
}

void hl_js_session_destroy(HlJsSession *s)
{
    if (!s) return;
    if (s->ctx) JS_FreeContext(s->ctx);
    if (s->rt) JS_FreeRuntime(s->rt);
    for (size_t i = 0; i < s->mod_count; i++) free(s->mods[i].bc);
    free(s->mods);
    free(s);
}

/* Drain the job queue until settled; returns 0 ok, -1 on a job exception. */
static int drain_jobs(HlJsSession *s)
{
    JSContext *ctx1;
    for (;;) {
        int r = JS_ExecutePendingJob(s->rt, &ctx1);
        if (r < 0) return -1;   /* a pending job threw */
        if (r == 0) return 0;   /* no more jobs */
    }
}

/* Load the entry module once (idempotent per session) from its precompiled bytecode,
 * registering globalThis.__hull_frontend. No eval hook is used. */
static int ensure_entry_loaded(HlJsSession *s, const char *module, char **out_json, size_t *out_len)
{
    if (s->entry_name[0] && strcmp(s->entry_name, module) == 0) return 0;   /* already loaded */

    const HlJsBcModule *m = find_module(s, module);
    if (!m) return fail_indeterminate(out_json, out_len, "js.internal", "tooling entry module not found");

    /* The instruction budget is reset ONCE at invocation entry (in hl_js_session_analyze),
     * so the one-time entry load counts against the same fresh budget as everything else. */
    JSValue mod = JS_ReadObject(s->ctx, m->bc, m->bc_len, JS_READ_OBJ_BYTECODE);
    if (JS_IsException(mod)) {
        JS_FreeValue(s->ctx, mod);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    /* Resolve the entry's imports (triggers the loader for each dep) before evaluating. */
    if (JS_ResolveModule(s->ctx, mod) < 0) {
        JS_FreeValue(s->ctx, mod);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    JSValue v = JS_EvalFunction(s->ctx, mod);   /* consumes `mod` */
    if (JS_IsException(v)) {
        JS_FreeValue(s->ctx, v);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    /* Module eval yields a promise; run its jobs and check it fulfilled. A job that failed
     * on a resource breach (interrupt / heap / stack) has a pending exception -- classify it
     * uniformly FIRST, before inspecting an ordinary promise rejection. */
    int drained = drain_jobs(s);
    if (drained != 0) {
        JS_FreeValue(s->ctx, v);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    if (JS_IsObject(v) && JS_PromiseState(s->ctx, v) == JS_PROMISE_REJECTED) {
        JSValue res = JS_PromiseResult(s->ctx, v);
        char *msg = jsvalue_to_message(s->ctx, res, "tooling entry rejected");
        JS_FreeValue(s->ctx, res);
        JS_FreeValue(s->ctx, v);
        int rc = fail_indeterminate(out_json, out_len, "js.internal", msg);
        free(msg);
        return rc;
    }
    JS_FreeValue(s->ctx, v);
    snprintf(s->entry_name, sizeof(s->entry_name), "%s", module);
    return 0;
}

int hl_js_session_analyze(HlJsSession *s, const char *module, const char *method,
                          const uint8_t *src, size_t src_len,
                          const char *path,
                          const char *options_json, size_t options_len,
                          char **out_json, size_t *out_len)
{
    if (out_json) *out_json = NULL;
    if (out_len) *out_len = 0;
    if (!s || !module || !method)
        return fail_indeterminate(out_json, out_len, "js.internal", "invalid arguments");
    /* Fail-closed transport: a NULL pointer with a nonzero length (source OR options) would
     * read past the placeholder buffer. Reject both before entering QuickJS. */
    if (src_len > 0 && !src)
        return fail_indeterminate(out_json, out_len, "js.transport", "null source with nonzero length");
    if (options_len > 0 && !options_json)
        return fail_indeterminate(out_json, out_len, "js.transport", "null options with nonzero length");
    if (src_len > s->limits.max_source_bytes)
        return fail_indeterminate(out_json, out_len, "js.limit.bytes", "source exceeds max_source_bytes");

    /* One fresh work budget + fresh resource markers for the WHOLE invocation: the one-time
     * entry load, options parsing, argument construction, the call, module jobs, and result
     * serialization all count against this single reset (not just JS_Call). stack_base anchors
     * the interrupt stack guard to this invocation's frame. */
    s->instr_count = 0;
    s->oom_hit = 0;
    s->stack_hit = 0;
    s->stack_base = stack_ptr_now();

    if (ensure_entry_loaded(s, module, out_json, out_len) != 0) return -1;

    JSContext *ctx = s->ctx;

    /* Reach the trusted entry object + method. A property read can itself throw (e.g. OOM);
     * route that through the unified classifier so no exception is left pending, rather than
     * misreading it as "entry missing" / "method not a function". */
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue fe = JS_GetPropertyStr(ctx, g, "__hull_frontend");
    JS_FreeValue(ctx, g);
    if (JS_IsException(fe)) {
        JS_FreeValue(ctx, fe);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    if (!JS_IsObject(fe)) {
        JS_FreeValue(ctx, fe);
        return fail_indeterminate(out_json, out_len, "js.internal", "entry did not register __hull_frontend");
    }
    JSValue fn = JS_GetPropertyStr(ctx, fe, method);
    if (JS_IsException(fn)) {
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    if (!JS_IsFunction(ctx, fn)) {
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_indeterminate(out_json, out_len, "js.internal", "entry method is not a function");
    }

    /* Options first (untrusted-shaped transport): JSON.parse length-aware, fail closed on
     * malformed / NUL-bearing / trailing-garbage input rather than silently nulling it. */
    JSValue arg_opts = JS_NULL;
    if (options_json && options_len > 0) {
        arg_opts = JS_ParseJSON(ctx, options_json, options_len, "<options>");
        if (JS_IsException(arg_opts)) {
            JS_FreeValue(ctx, arg_opts);
            JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
            /* Ordinary malformed input is js.transport; a resource breach during the parse
             * (heap/instructions) is classified as the matching js.limit.*. */
            return fail_from_exception(s, ctx, out_json, out_len, "js.transport");
        }
    }

    /* Source as an ArrayBuffer (length-aware, NUL-safe). src is guaranteed non-NULL when
     * src_len > 0 (checked above); for a zero-length source a placeholder ptr is fine. */
    JSValue arg_src = JS_NewArrayBufferCopy(ctx, src ? src : (const uint8_t *)"", src_len);
    JSValue arg_path = JS_NewStringLen(ctx, path ? path : "", path ? strlen(path) : 0);
    /* Argument construction fails only under memory pressure. A valid source that does not
     * fit the configured heap is js.limit.heap (classified from the preserved exception),
     * NOT malformed transport. */
    if (JS_IsException(arg_src) || JS_IsException(arg_path)) {
        JS_FreeValue(ctx, arg_src); JS_FreeValue(ctx, arg_path); JS_FreeValue(ctx, arg_opts);
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    JSValue argv[3] = { arg_src, arg_path, arg_opts };

    JSValue result = JS_Call(ctx, fn, JS_UNDEFINED, 3, argv);
    JS_FreeValue(ctx, argv[0]); JS_FreeValue(ctx, argv[1]); JS_FreeValue(ctx, argv[2]);
    JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);

    if (JS_IsException(result)) {
        JS_FreeValue(ctx, result);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    /* Authoritative override: a genuine resource breach that the frontend nonetheless CONTAINED
     * (a soft OOM whose catch survived because unwinding freed enough) is still a host breach.
     * The marker -- not the returned SourceUnit -- decides, so it is reported js.limit.* here
     * rather than being emitted as the frontend's js.internal placeholder. */
    if (s->oom_hit || s->stack_hit) {
        JS_FreeValue(ctx, result);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }

    /* Serialize the frontend-neutral facts. AST/session state never crosses here. */
    JSValue json = JS_JSONStringify(ctx, result, JS_UNDEFINED, JS_UNDEFINED);
    JS_FreeValue(ctx, result);
    if (JS_IsException(json)) {
        JS_FreeValue(ctx, json);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    /* The boundary contract is VALIDATED JSON. JSON.stringify(undefined) (a method that
     * returns undefined / a function / a bare symbol) yields the JS value `undefined`, NOT
     * a string -- JS_ToCStringLen would then emit the bytes "undefined". Require a string
     * and fail closed otherwise, so it never knowingly emits non-JSON. */
    if (!JS_IsString(json)) {
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.internal",
                                  "tooling result was not JSON (JSON.stringify returned a non-string)");
    }
    size_t jlen = 0;
    const char *js = JS_ToCStringLen(ctx, &jlen, json);
    if (!js) {
        JS_FreeValue(ctx, json);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    if (jlen > s->limits.max_result_bytes) {
        JS_FreeCString(ctx, js);
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.limit.result", "result exceeds max_result_bytes");
    }
    char *copy = malloc(jlen + 1);
    if (!copy) {
        JS_FreeCString(ctx, js);
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.internal", "out of memory");
    }
    memcpy(copy, js, jlen);
    copy[jlen] = '\0';
    JS_FreeCString(ctx, js);
    JS_FreeValue(ctx, json);

    if (out_json) *out_json = copy; else free(copy);
    if (out_len) *out_len = jlen;
    return 0;
}
