/*
 * frontend/js_session.c - the restricted QuickJS tooling runtime (Slice 1).
 * See include/hull/frontend/js_session.h + docs/javascript_source_frontend_design.md.
 *
 * The session context NEVER enables the QuickJS eval hook (JS_AddIntrinsicEval), so every
 * dynamic-compile path (eval, Function, and the prototype-reachable constructors) throws
 * "eval is not supported". The trusted cli-js bundle is compiled to bytecode ONCE in a
 * throwaway eval-enabled context at create time and loaded into the session via
 * JS_ReadObject, which needs no eval hook.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
#include "hull/frontend/js_session.h"

#include "quickjs.h"
#include "hull/entry.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* The bundled cli-js tooling registry (generated by the Makefile from stdlib/cli/js).
 * Loaded ONLY into this tooling runtime -- never the application JS runtime. A
 * name-NULL sentinel terminates the array. */
extern const HlEntry hl_stdlib_js_cli_entries[];

/* One precompiled tooling module: its registry name (borrowed, stable) + owned bytecode. */
typedef struct {
    const char *name;
    uint8_t    *bc;
    size_t      bc_len;
} HlJsBcModule;

struct HlJsSession {
    JSRuntime        *rt;
    JSContext        *ctx;
    HlJsSessionLimits limits;
    int64_t           instr_count;     /* interrupt polls seen in the current invocation */
    int64_t           instr_limit;     /* == limits.max_instructions (0 = unlimited) */
    char              entry_name[128]; /* the loaded __hull_frontend entry, or "" */
    HlJsBcModule     *mods;            /* precompiled bytecode, one per cli-js entry */
    size_t            mod_count;
};

/* ── instruction budget ─────────────────────────────────────────────────── */
static int session_interrupt(JSRuntime *rt, void *opaque)
{
    (void)rt;
    HlJsSession *s = (HlJsSession *)opaque;
    s->instr_count++;
    return (s->instr_limit > 0 && s->instr_count > s->instr_limit) ? 1 : 0;
}

/* ── bytecode module map ────────────────────────────────────────────────── */
static const HlJsBcModule *find_module(const HlJsSession *s, const char *name)
{
    for (size_t i = 0; i < s->mod_count; i++)
        if (strcmp(s->mods[i].name, name) == 0) return &s->mods[i];
    return NULL;
}

/* Tooling-only module loader: the SESSION resolves an import by deserializing the
 * module's precompiled bytecode (no eval hook, no filesystem, no app modules). */
static char *session_module_normalize(JSContext *ctx, const char *base_name,
                                      const char *name, void *opaque)
{
    (void)base_name; (void)opaque;
    /* The bundle uses ONLY absolute `hull:*` module names -- identity normalization. */
    return js_strdup(ctx, name);
}

static JSModuleDef *session_module_loader(JSContext *ctx, const char *module_name, void *opaque)
{
    HlJsSession *s = (HlJsSession *)opaque;
    const HlJsBcModule *m = find_module(s, module_name);
    if (!m) {
        JS_ThrowReferenceError(ctx, "tooling module not found: %s", module_name);
        return NULL;
    }
    JSValue v = JS_ReadObject(ctx, m->bc, m->bc_len, JS_READ_OBJ_BYTECODE);
    if (JS_IsException(v)) return NULL;   /* the pending exception is the read failure */
    JSModuleDef *md = (JSModuleDef *)JS_VALUE_GET_PTR(v);
    JS_FreeValue(ctx, v);                 /* the module stays owned by ctx's module list */
    return md;
}

/* ── diagnostics (structured indeterminate result, never a raw exception) ── */
static char *json_escape_dup(const char *s)
{
    /* Minimal JSON string-escaper for a diagnostic message (bounded). */
    size_t n = s ? strlen(s) : 0;
    /* worst case per input byte is a 6-char \uXXXX escape, + the NUL terminator */
    size_t cap = n * 6 + 1;
    char *out = malloc(cap);
    if (!out) return NULL;
    char *p = out;
    char *end = out + cap;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '"' || c == '\\') { *p++ = '\\'; *p++ = (char)c; }
        else if (c == '\n') { *p++ = '\\'; *p++ = 'n'; }
        else if (c == '\r') { *p++ = '\\'; *p++ = 'r'; }
        else if (c == '\t') { *p++ = '\\'; *p++ = 't'; }
        else if (c < 0x20) { p += snprintf(p, (size_t)(end - p), "\\u%04x", c); }
        else { *p++ = (char)c; }
    }
    *p = '\0';
    return out;
}

static int fail_indeterminate(char **out_json, size_t *out_len, const char *code, const char *msg)
{
    char *emsg = json_escape_dup(msg ? msg : "");
    const char *safe = emsg ? emsg : "";
    size_t cap = strlen(code) + strlen(safe) + 128;
    char *j = malloc(cap);
    if (j) {
        int n = snprintf(j, cap,
            "{\"status\":\"indeterminate\",\"diagnostics\":"
            "[{\"severity\":\"error\",\"code\":\"%s\",\"message\":\"%s\"}]}",
            code, safe);
        /* Match the success path: hand ownership to the caller, else free (no leak). */
        if (out_json) *out_json = j; else free(j);
        if (out_len) *out_len = (n > 0) ? (size_t)n : 0;
    } else {
        if (out_json) *out_json = NULL;
        if (out_len) *out_len = 0;
    }
    free(emsg);
    return -1;
}

/* Convert an arbitrary JSValue to a best-effort heap C string. If JS_ToCString itself fails
 * (typically OOM while stringifying) it returns NULL AND raises a SECONDARY pending
 * exception; this helper clears that exception so it can't contaminate the next invocation
 * on a reused session. Returns a malloc'd string (caller frees), or NULL only on strdup OOM.
 * Shared by the pending-exception path and the rejected-promise-value path. */
static char *jsvalue_to_message(JSContext *ctx, JSValueConst val, const char *fallback)
{
    const char *cs = JS_ToCString(ctx, val);
    if (cs) {
        char *out = strdup(cs);
        JS_FreeCString(ctx, cs);
        return out;
    }
    JS_FreeValue(ctx, JS_GetException(ctx));   /* clear the secondary conversion exception */
    return strdup(fallback);
}

/* Pull the pending JS exception into a heap C string (best-effort). */
static char *take_exception_message(JSContext *ctx)
{
    JSValue exc = JS_GetException(ctx);
    char *out = jsvalue_to_message(ctx, exc, "unknown tooling exception");
    JS_FreeValue(ctx, exc);
    return out;
}

/* Consume the pending QuickJS exception and fail the invocation with the correctly
 * classified code. Used at EVERY phase (options parse, argument construction, module-job
 * draining, JS_Call, JS_JSONStringify, JS_ToCStringLen) so a resource breach is reported
 * as the same js.limit.* code regardless of which phase tripped it. The instruction-budget
 * breach is authoritative (the interrupt error is uncatchable); heap / stack exhaustion is
 * recognized from the preserved QuickJS message; otherwise the caller's `fallback` applies
 * (js.transport for malformed input, js.internal for an ordinary tooling fault). */
static int fail_from_exception(HlJsSession *s, JSContext *ctx,
                               char **out_json, size_t *out_len, const char *fallback)
{
    char *msg = take_exception_message(ctx);   /* reads + clears the pending exception */
    const char *code;
    if (s->instr_limit > 0 && s->instr_count > s->instr_limit)      code = "js.limit.instructions";
    else if (msg && strstr(msg, "out of memory"))                  code = "js.limit.heap";
    else if (msg && strstr(msg, "stack overflow"))                 code = "js.limit.stack";
    else                                                            code = fallback;
    int rc = fail_indeterminate(out_json, out_len, code, msg);
    free(msg);
    return rc;
}

/* ── bundle precompile (throwaway eval-enabled context) ─────────────────── */
/* The compiler context needs a module loader so a module's `import`s resolve while it is
 * COMPILE_ONLY-compiled: QuickJS resolves import specifiers against the loader on demand
 * (recursively compiling dependencies from source), so the bundle compiles regardless of the
 * (alphabetical) registry order -- a module may import a sibling that sorts after it. */
static char *precompile_module_normalize(JSContext *ctx, const char *base_name,
                                         const char *name, void *opaque)
{
    (void)base_name; (void)opaque;
    return js_strdup(ctx, name);      /* absolute `hull:*` specifiers -- identity */
}

static JSModuleDef *precompile_module_loader(JSContext *ctx, const char *module_name, void *opaque)
{
    (void)opaque;
    for (const HlEntry *e = hl_stdlib_js_cli_entries; e->name; e++) {
        if (strcmp(e->name, module_name) == 0) {
            JSValue f = JS_Eval(ctx, (const char *)e->data, e->len, module_name,
                                JS_EVAL_TYPE_MODULE | JS_EVAL_FLAG_COMPILE_ONLY);
            if (JS_IsException(f)) return NULL;   /* pending exception is the syntax error */
            JSModuleDef *md = (JSModuleDef *)JS_VALUE_GET_PTR(f);
            JS_FreeValue(ctx, f);
            return md;
        }
    }
    JS_ThrowReferenceError(ctx, "tooling module not found: %s", module_name);
    return NULL;
}

/* Compile every cli-js tooling module to bytecode so the session can load them WITHOUT
 * enabling its own eval hook. Runs in a separate runtime/context that IS eval-enabled but
 * only ever sees the trusted, embedded bundle. Returns 0 on success, -1 on any failure
 * (a bundled tool that fails to compile is a build defect). */
static int precompile_bundle(HlJsSession *s)
{
    size_t n = 0;
    while (hl_stdlib_js_cli_entries[n].name) n++;
    s->mods = calloc(n ? n : 1, sizeof(*s->mods));
    if (!s->mods) return -1;
    s->mod_count = 0;

    /* The compiler context uses generous DEFAULT limits, decoupled from the (possibly
     * tiny, test-chosen) session limits, so precompiling the bundle never trips them. */
    JSRuntime *crt = JS_NewRuntime();
    if (!crt) return -1;
    HlJsSessionLimits def = HL_JS_SESSION_LIMITS_DEFAULT;
    JS_SetMemoryLimit(crt, def.max_heap_bytes);
    JS_SetMaxStackSize(crt, def.max_stack_bytes);
    JSContext *cctx = JS_NewContextRaw(crt);
    if (!cctx) { JS_FreeRuntime(crt); return -1; }
    JS_AddIntrinsicBaseObjects(cctx);
    JS_AddIntrinsicEval(cctx);            /* needed to COMPILE source -> bytecode */
    JS_AddIntrinsicRegExpCompiler(cctx);  /* module source may carry regex literals */
    JS_AddIntrinsicRegExp(cctx);
    /* Resolve inter-module imports from the registry on demand (order-independent). */
    JS_SetModuleLoaderFunc(crt, precompile_module_normalize, precompile_module_loader, NULL);

    int rc = 0;
    for (const HlEntry *e = hl_stdlib_js_cli_entries; e->name; e++) {
        JSValue f = JS_Eval(cctx, (const char *)e->data, e->len, e->name,
                            JS_EVAL_TYPE_MODULE | JS_EVAL_FLAG_COMPILE_ONLY);
        if (JS_IsException(f)) {
            JS_FreeValue(cctx, JS_GetException(cctx));
            JS_FreeValue(cctx, f);
            rc = -1; break;
        }
        size_t out_len = 0;
        uint8_t *bc = JS_WriteObject(cctx, &out_len, f, JS_WRITE_OBJ_BYTECODE);
        JS_FreeValue(cctx, f);
        if (!bc || out_len == 0) { if (bc) js_free(cctx, bc); rc = -1; break; }
        uint8_t *copy = malloc(out_len);
        if (!copy) { js_free(cctx, bc); rc = -1; break; }
        memcpy(copy, bc, out_len);
        js_free(cctx, bc);
        s->mods[s->mod_count].name   = e->name;   /* borrowed from the static registry */
        s->mods[s->mod_count].bc     = copy;
        s->mods[s->mod_count].bc_len = out_len;
        s->mod_count++;
    }

    JS_FreeContext(cctx);
    JS_FreeRuntime(crt);
    return rc;
}

/* ── lifecycle ──────────────────────────────────────────────────────────── */
HlJsSession *hl_js_session_create(const HlJsSessionLimits *limits)
{
    HlJsSession *s = calloc(1, sizeof(*s));
    if (!s) return NULL;
    HlJsSessionLimits def = HL_JS_SESSION_LIMITS_DEFAULT;
    s->limits = limits ? *limits : def;
    s->instr_limit = s->limits.max_instructions;
    s->entry_name[0] = '\0';

    if (precompile_bundle(s) != 0) { hl_js_session_destroy(s); return NULL; }

    s->rt = JS_NewRuntime();
    if (!s->rt) { hl_js_session_destroy(s); return NULL; }
    JS_SetMemoryLimit(s->rt, s->limits.max_heap_bytes);
    JS_SetMaxStackSize(s->rt, s->limits.max_stack_bytes);
    JS_SetInterruptHandler(s->rt, session_interrupt, s);
    JS_SetModuleLoaderFunc(s->rt, session_module_normalize, session_module_loader, s);

    s->ctx = JS_NewContextRaw(s->rt);
    if (!s->ctx) { hl_js_session_destroy(s); return NULL; }

    /* Only what the PARSER needs. Crucially NOT JS_AddIntrinsicEval: the session's eval hook
     * stays NULL, so eval / Function / constructor-reachable dynamic compilation all throw
     * "eval is not supported". The trusted bundle loads from bytecode instead. */
    JS_AddIntrinsicBaseObjects(s->ctx);
    JS_AddIntrinsicStringNormalize(s->ctx);
    JS_AddIntrinsicRegExpCompiler(s->ctx);   /* regex compilation (not JS eval) */
    JS_AddIntrinsicRegExp(s->ctx);
    JS_AddIntrinsicJSON(s->ctx);
    JS_AddIntrinsicMapSet(s->ctx);
    JS_AddIntrinsicTypedArrays(s->ctx);
    JS_AddIntrinsicPromise(s->ctx);          /* module evaluation returns a promise */

    /* Defense in depth: delete the global eval / Function bindings too. Reaching them via a
     * prototype still lands on the disabled eval hook, but removing the obvious names keeps
     * the surface clean and self-documenting. */
    JSValue g = JS_GetGlobalObject(s->ctx);
    JSAtom a_eval = JS_NewAtom(s->ctx, "eval");
    JS_DeleteProperty(s->ctx, g, a_eval, 0);
    JS_FreeAtom(s->ctx, a_eval);
    JSAtom a_fn = JS_NewAtom(s->ctx, "Function");
    JS_DeleteProperty(s->ctx, g, a_fn, 0);
    JS_FreeAtom(s->ctx, a_fn);
    JS_FreeValue(s->ctx, g);

    return s;
}

void hl_js_session_destroy(HlJsSession *s)
{
    if (!s) return;
    if (s->ctx) JS_FreeContext(s->ctx);
    if (s->rt) JS_FreeRuntime(s->rt);
    for (size_t i = 0; i < s->mod_count; i++) free(s->mods[i].bc);
    free(s->mods);
    free(s);
}

/* Drain the job queue until settled; returns 0 ok, -1 on a job exception. */
static int drain_jobs(HlJsSession *s)
{
    JSContext *ctx1;
    for (;;) {
        int r = JS_ExecutePendingJob(s->rt, &ctx1);
        if (r < 0) return -1;   /* a pending job threw */
        if (r == 0) return 0;   /* no more jobs */
    }
}

/* Load the entry module once (idempotent per session) from its precompiled bytecode,
 * registering globalThis.__hull_frontend. No eval hook is used. */
static int ensure_entry_loaded(HlJsSession *s, const char *module, char **out_json, size_t *out_len)
{
    if (s->entry_name[0] && strcmp(s->entry_name, module) == 0) return 0;   /* already loaded */

    const HlJsBcModule *m = find_module(s, module);
    if (!m) return fail_indeterminate(out_json, out_len, "js.internal", "tooling entry module not found");

    /* The instruction budget is reset ONCE at invocation entry (in hl_js_session_analyze),
     * so the one-time entry load counts against the same fresh budget as everything else. */
    JSValue mod = JS_ReadObject(s->ctx, m->bc, m->bc_len, JS_READ_OBJ_BYTECODE);
    if (JS_IsException(mod)) {
        JS_FreeValue(s->ctx, mod);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    /* Resolve the entry's imports (triggers the loader for each dep) before evaluating. */
    if (JS_ResolveModule(s->ctx, mod) < 0) {
        JS_FreeValue(s->ctx, mod);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    JSValue v = JS_EvalFunction(s->ctx, mod);   /* consumes `mod` */
    if (JS_IsException(v)) {
        JS_FreeValue(s->ctx, v);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    /* Module eval yields a promise; run its jobs and check it fulfilled. A job that failed
     * on a resource breach (interrupt / heap / stack) has a pending exception -- classify it
     * uniformly FIRST, before inspecting an ordinary promise rejection. */
    int drained = drain_jobs(s);
    if (drained != 0) {
        JS_FreeValue(s->ctx, v);
        return fail_from_exception(s, s->ctx, out_json, out_len, "js.internal");
    }
    if (JS_IsObject(v) && JS_PromiseState(s->ctx, v) == JS_PROMISE_REJECTED) {
        JSValue res = JS_PromiseResult(s->ctx, v);
        char *msg = jsvalue_to_message(s->ctx, res, "tooling entry rejected");
        JS_FreeValue(s->ctx, res);
        JS_FreeValue(s->ctx, v);
        int rc = fail_indeterminate(out_json, out_len, "js.internal", msg);
        free(msg);
        return rc;
    }
    JS_FreeValue(s->ctx, v);
    snprintf(s->entry_name, sizeof(s->entry_name), "%s", module);
    return 0;
}

int hl_js_session_analyze(HlJsSession *s, const char *module, const char *method,
                          const uint8_t *src, size_t src_len,
                          const char *path,
                          const char *options_json, size_t options_len,
                          char **out_json, size_t *out_len)
{
    if (out_json) *out_json = NULL;
    if (out_len) *out_len = 0;
    if (!s || !module || !method)
        return fail_indeterminate(out_json, out_len, "js.internal", "invalid arguments");
    /* Fail-closed transport: a NULL pointer with a nonzero length (source OR options) would
     * read past the placeholder buffer. Reject both before entering QuickJS. */
    if (src_len > 0 && !src)
        return fail_indeterminate(out_json, out_len, "js.transport", "null source with nonzero length");
    if (options_len > 0 && !options_json)
        return fail_indeterminate(out_json, out_len, "js.transport", "null options with nonzero length");
    if (src_len > s->limits.max_source_bytes)
        return fail_indeterminate(out_json, out_len, "js.limit.bytes", "source exceeds max_source_bytes");

    /* One fresh work budget for the WHOLE invocation: the one-time entry load, options
     * parsing, argument construction, the call, module jobs, and result serialization all
     * count against this single reset (not just JS_Call). */
    s->instr_count = 0;

    if (ensure_entry_loaded(s, module, out_json, out_len) != 0) return -1;

    JSContext *ctx = s->ctx;

    /* Reach the trusted entry object + method. A property read can itself throw (e.g. OOM);
     * route that through the unified classifier so no exception is left pending, rather than
     * misreading it as "entry missing" / "method not a function". */
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue fe = JS_GetPropertyStr(ctx, g, "__hull_frontend");
    JS_FreeValue(ctx, g);
    if (JS_IsException(fe)) {
        JS_FreeValue(ctx, fe);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    if (!JS_IsObject(fe)) {
        JS_FreeValue(ctx, fe);
        return fail_indeterminate(out_json, out_len, "js.internal", "entry did not register __hull_frontend");
    }
    JSValue fn = JS_GetPropertyStr(ctx, fe, method);
    if (JS_IsException(fn)) {
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    if (!JS_IsFunction(ctx, fn)) {
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_indeterminate(out_json, out_len, "js.internal", "entry method is not a function");
    }

    /* Options first (untrusted-shaped transport): JSON.parse length-aware, fail closed on
     * malformed / NUL-bearing / trailing-garbage input rather than silently nulling it. */
    JSValue arg_opts = JS_NULL;
    if (options_json && options_len > 0) {
        arg_opts = JS_ParseJSON(ctx, options_json, options_len, "<options>");
        if (JS_IsException(arg_opts)) {
            JS_FreeValue(ctx, arg_opts);
            JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
            /* Ordinary malformed input is js.transport; a resource breach during the parse
             * (heap/instructions) is classified as the matching js.limit.*. */
            return fail_from_exception(s, ctx, out_json, out_len, "js.transport");
        }
    }

    /* Source as an ArrayBuffer (length-aware, NUL-safe). src is guaranteed non-NULL when
     * src_len > 0 (checked above); for a zero-length source a placeholder ptr is fine. */
    JSValue arg_src = JS_NewArrayBufferCopy(ctx, src ? src : (const uint8_t *)"", src_len);
    JSValue arg_path = JS_NewStringLen(ctx, path ? path : "", path ? strlen(path) : 0);
    /* Argument construction fails only under memory pressure. A valid source that does not
     * fit the configured heap is js.limit.heap (classified from the preserved exception),
     * NOT malformed transport. */
    if (JS_IsException(arg_src) || JS_IsException(arg_path)) {
        JS_FreeValue(ctx, arg_src); JS_FreeValue(ctx, arg_path); JS_FreeValue(ctx, arg_opts);
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    JSValue argv[3] = { arg_src, arg_path, arg_opts };

    JSValue result = JS_Call(ctx, fn, JS_UNDEFINED, 3, argv);
    JS_FreeValue(ctx, argv[0]); JS_FreeValue(ctx, argv[1]); JS_FreeValue(ctx, argv[2]);
    JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);

    if (JS_IsException(result)) {
        JS_FreeValue(ctx, result);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }

    /* Serialize the frontend-neutral facts. AST/session state never crosses here. */
    JSValue json = JS_JSONStringify(ctx, result, JS_UNDEFINED, JS_UNDEFINED);
    JS_FreeValue(ctx, result);
    if (JS_IsException(json)) {
        JS_FreeValue(ctx, json);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    /* The boundary contract is VALIDATED JSON. JSON.stringify(undefined) (a method that
     * returns undefined / a function / a bare symbol) yields the JS value `undefined`, NOT
     * a string -- JS_ToCStringLen would then emit the bytes "undefined". Require a string
     * and fail closed otherwise, so Slice 1 never knowingly emits non-JSON. */
    if (!JS_IsString(json)) {
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.internal",
                                  "tooling result was not JSON (JSON.stringify returned a non-string)");
    }
    size_t jlen = 0;
    const char *js = JS_ToCStringLen(ctx, &jlen, json);
    if (!js) {
        JS_FreeValue(ctx, json);
        return fail_from_exception(s, ctx, out_json, out_len, "js.internal");
    }
    if (jlen > s->limits.max_result_bytes) {
        JS_FreeCString(ctx, js);
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.limit.result", "result exceeds max_result_bytes");
    }
    char *copy = malloc(jlen + 1);
    if (!copy) {
        JS_FreeCString(ctx, js);
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.internal", "out of memory");
    }
    memcpy(copy, js, jlen);
    copy[jlen] = '\0';
    JS_FreeCString(ctx, js);
    JS_FreeValue(ctx, json);

    if (out_json) *out_json = copy; else free(copy);
    if (out_len) *out_len = jlen;
    return 0;
}
