/*
 * frontend/js_session.c — the restricted QuickJS tooling runtime (Slice 1).
 * See include/hull/frontend/js_session.h + docs/javascript_source_frontend_design.md.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
#include "hull/frontend/js_session.h"

#include "quickjs.h"
#include "hull/vfs.h"
#include "hull/entry.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* The bundled cli-js tooling registry (generated by the Makefile from stdlib/cli/js).
 * Loaded ONLY into this tooling runtime -- never the application JS runtime. */
extern const HlEntry hl_stdlib_js_cli_entries[];

struct HlJsSession {
    JSRuntime        *rt;
    JSContext        *ctx;
    HlVfs             vfs;              /* over hl_stdlib_js_cli_entries -- tooling modules only */
    HlJsSessionLimits limits;
    int64_t           instr_count;     /* per-invocation instruction counter */
    int64_t           instr_limit;     /* mirror of limits.max_instructions for the handler */
    char              entry_name[128]; /* the currently-loaded entry module ("" = none) */
};

/* ── instruction budget ─────────────────────────────────────────────────── */
static int session_interrupt(JSRuntime *rt, void *opaque)
{
    (void)rt;
    HlJsSession *s = (HlJsSession *)opaque;
    s->instr_count++;
    return (s->instr_limit > 0 && s->instr_count > s->instr_limit) ? 1 : 0;
}

/* ── tooling-only module loader (cli-js VFS; no app modules, no filesystem) ── */
static char *session_module_normalize(JSContext *ctx, const char *base_name,
                                      const char *name, void *opaque)
{
    (void)base_name; (void)opaque;
    /* The bundle uses ONLY absolute `hull:*` module names -- identity normalization. A
     * relative/filesystem specifier is not part of the trusted bundle; return it as-is so
     * the loader below fails it closed (VFS miss -> ReferenceError, not a file open). */
    return js_strdup(ctx, name);
}

static JSModuleDef *session_module_loader(JSContext *ctx, const char *module_name, void *opaque)
{
    HlJsSession *s = (HlJsSession *)opaque;
    const HlEntry *e = hl_vfs_find(&s->vfs, module_name);
    if (!e) {
        JS_ThrowReferenceError(ctx, "tooling module not found: %s", module_name);
        return NULL;
    }
    /* Compile-only: parse the module into a JSModuleDef without running it. */
    JSValue func = JS_Eval(ctx, (const char *)e->data, e->len, module_name,
                           JS_EVAL_TYPE_MODULE | JS_EVAL_FLAG_COMPILE_ONLY);
    if (JS_IsException(func)) {
        return NULL;   /* the pending exception is the syntax error; caller converts it */
    }
    JSModuleDef *m = (JSModuleDef *)JS_VALUE_GET_PTR(func);
    JS_FreeValue(ctx, func);
    return m;
}

/* ── diagnostics (structured indeterminate result, never a raw exception) ── */
static char *json_escape_dup(const char *s)
{
    /* Minimal JSON string-escaper for a diagnostic message (bounded). */
    size_t n = s ? strlen(s) : 0;
    /* worst case per input byte is a 6-char \uXXXX escape, + the NUL terminator */
    size_t cap = n * 6 + 1;
    char *out = malloc(cap);
    if (!out) return NULL;
    char *p = out;
    char *end = out + cap;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '"' || c == '\\') { *p++ = '\\'; *p++ = (char)c; }
        else if (c == '\n') { *p++ = '\\'; *p++ = 'n'; }
        else if (c == '\r') { *p++ = '\\'; *p++ = 'r'; }
        else if (c == '\t') { *p++ = '\\'; *p++ = 't'; }
        else if (c < 0x20) { p += snprintf(p, (size_t)(end - p), "\\u%04x", c); }
        else { *p++ = (char)c; }
    }
    *p = '\0';
    return out;
}

static int fail_indeterminate(char **out_json, size_t *out_len, const char *code, const char *msg)
{
    char *emsg = json_escape_dup(msg ? msg : "");
    const char *safe = emsg ? emsg : "";
    size_t cap = strlen(code) + strlen(safe) + 128;
    char *j = malloc(cap);
    if (j) {
        int n = snprintf(j, cap,
            "{\"status\":\"indeterminate\",\"diagnostics\":"
            "[{\"severity\":\"error\",\"code\":\"%s\",\"message\":\"%s\"}]}",
            code, safe);
        if (out_json) *out_json = j;
        if (out_len) *out_len = (n > 0) ? (size_t)n : 0;
    } else {
        if (out_json) *out_json = NULL;
        if (out_len) *out_len = 0;
    }
    free(emsg);
    return -1;
}

/* Pull the pending JS exception into a heap C string (best-effort). */
static char *take_exception_message(JSContext *ctx)
{
    JSValue exc = JS_GetException(ctx);
    const char *cs = JS_ToCString(ctx, exc);
    char *out = cs ? strdup(cs) : strdup("unknown tooling exception");
    if (cs) JS_FreeCString(ctx, cs);
    JS_FreeValue(ctx, exc);
    return out;
}

/* ── lifecycle ──────────────────────────────────────────────────────────── */
HlJsSession *hl_js_session_create(const HlJsSessionLimits *limits)
{
    HlJsSession *s = calloc(1, sizeof(*s));
    if (!s) return NULL;
    HlJsSessionLimits def = HL_JS_SESSION_LIMITS_DEFAULT;
    s->limits = limits ? *limits : def;
    s->instr_limit = s->limits.max_instructions;
    s->entry_name[0] = '\0';

    hl_vfs_init(&s->vfs, hl_stdlib_js_cli_entries, NULL);

    s->rt = JS_NewRuntime();
    if (!s->rt) { free(s); return NULL; }
    JS_SetMemoryLimit(s->rt, s->limits.max_heap_bytes);
    JS_SetMaxStackSize(s->rt, s->limits.max_stack_bytes);
    JS_SetInterruptHandler(s->rt, session_interrupt, s);
    JS_SetModuleLoaderFunc(s->rt, session_module_normalize, session_module_loader, s);

    s->ctx = JS_NewContextRaw(s->rt);
    if (!s->ctx) { JS_FreeRuntime(s->rt); free(s); return NULL; }

    /* Only what the PARSER needs. NOT: Date, Proxy, WeakRef, BigDecimal, and (below) no
     * JS-level eval / Function. `eval` intrinsic is added so the C-level JS_Eval that runs
     * the bundle works, then the `eval` + `Function` globals are deleted. */
    JS_AddIntrinsicBaseObjects(s->ctx);
    JS_AddIntrinsicEval(s->ctx);
    JS_AddIntrinsicStringNormalize(s->ctx);
    JS_AddIntrinsicRegExpCompiler(s->ctx);
    JS_AddIntrinsicRegExp(s->ctx);
    JS_AddIntrinsicJSON(s->ctx);
    JS_AddIntrinsicMapSet(s->ctx);
    JS_AddIntrinsicTypedArrays(s->ctx);
    JS_AddIntrinsicPromise(s->ctx);   /* module evaluation returns a promise */

    /* Strip JS-level dynamic code execution: eval() + the Function constructor. */
    JSValue g = JS_GetGlobalObject(s->ctx);
    JSAtom a_eval = JS_NewAtom(s->ctx, "eval");
    JS_DeleteProperty(s->ctx, g, a_eval, 0);
    JS_FreeAtom(s->ctx, a_eval);
    JSAtom a_fn = JS_NewAtom(s->ctx, "Function");
    JS_DeleteProperty(s->ctx, g, a_fn, 0);
    JS_FreeAtom(s->ctx, a_fn);
    JS_FreeValue(s->ctx, g);

    return s;
}

void hl_js_session_destroy(HlJsSession *s)
{
    if (!s) return;
    if (s->ctx) JS_FreeContext(s->ctx);
    if (s->rt) JS_FreeRuntime(s->rt);
    free(s);
}

/* Drain the job queue until settled; returns 0 ok, -1 on a job exception. */
static int drain_jobs(HlJsSession *s)
{
    JSContext *ctx1;
    for (;;) {
        int r = JS_ExecutePendingJob(s->rt, &ctx1);
        if (r < 0) return -1;   /* a pending job threw */
        if (r == 0) return 0;   /* no more jobs */
    }
}

/* Evaluate the entry module once (idempotent per session), registering
 * globalThis.__hull_frontend. Cached across calls so the parser bundle loads once. */
static int ensure_entry_loaded(HlJsSession *s, const char *module, char **out_json, size_t *out_len)
{
    if (s->entry_name[0] && strcmp(s->entry_name, module) == 0) return 0;   /* already loaded */

    const HlEntry *e = hl_vfs_find(&s->vfs, module);
    if (!e) return fail_indeterminate(out_json, out_len, "js.internal", "tooling entry module not found");

    s->instr_count = 0;
    JSValue v = JS_Eval(s->ctx, (const char *)e->data, e->len, module, JS_EVAL_TYPE_MODULE);
    if (JS_IsException(v)) {
        char *m = take_exception_message(s->ctx);
        JS_FreeValue(s->ctx, v);
        int rc = fail_indeterminate(out_json, out_len, "js.internal", m);
        free(m);
        return rc;
    }
    /* Module eval yields a promise; run its jobs and check it fulfilled. */
    int drained = drain_jobs(s);
    if (JS_IsObject(v) && JS_PromiseState(s->ctx, v) == JS_PROMISE_REJECTED) {
        JSValue res = JS_PromiseResult(s->ctx, v);
        const char *cs = JS_ToCString(s->ctx, res);
        char *m = cs ? strdup(cs) : strdup("tooling entry rejected");
        if (cs) JS_FreeCString(s->ctx, cs);
        JS_FreeValue(s->ctx, res);
        JS_FreeValue(s->ctx, v);
        int rc = fail_indeterminate(out_json, out_len, "js.internal", m);
        free(m);
        return rc;
    }
    JS_FreeValue(s->ctx, v);
    if (drained != 0) {
        char *m = take_exception_message(s->ctx);
        int rc = fail_indeterminate(out_json, out_len, "js.internal", m);
        free(m);
        return rc;
    }
    snprintf(s->entry_name, sizeof(s->entry_name), "%s", module);
    return 0;
}

int hl_js_session_analyze(HlJsSession *s, const char *module, const char *method,
                          const uint8_t *src, size_t src_len,
                          const char *path, const char *options_json,
                          char **out_json, size_t *out_len)
{
    if (out_json) *out_json = NULL;
    if (out_len) *out_len = 0;
    if (!s || !module || !method)
        return fail_indeterminate(out_json, out_len, "js.internal", "invalid arguments");
    if (src_len > s->limits.max_source_bytes)
        return fail_indeterminate(out_json, out_len, "js.limit.bytes", "source exceeds max_source_bytes");

    if (ensure_entry_loaded(s, module, out_json, out_len) != 0) return -1;

    JSContext *ctx = s->ctx;

    /* Reach the trusted entry object + method. */
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue fe = JS_GetPropertyStr(ctx, g, "__hull_frontend");
    JS_FreeValue(ctx, g);
    if (!JS_IsObject(fe)) {
        JS_FreeValue(ctx, fe);
        return fail_indeterminate(out_json, out_len, "js.internal", "entry did not register __hull_frontend");
    }
    JSValue fn = JS_GetPropertyStr(ctx, fe, method);
    if (!JS_IsFunction(ctx, fn)) {
        JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);
        return fail_indeterminate(out_json, out_len, "js.internal", "entry method is not a function");
    }

    /* Args: raw source bytes as an ArrayBuffer (length-aware, NUL-safe), path, options. */
    JSValue arg_src = JS_NewArrayBufferCopy(ctx, src ? src : (const uint8_t *)"", src_len);
    JSValue arg_path = JS_NewStringLen(ctx, path ? path : "", path ? strlen(path) : 0);
    JSValue arg_opts;
    if (options_json && *options_json) {
        arg_opts = JS_ParseJSON(ctx, options_json, strlen(options_json), "<options>");
        if (JS_IsException(arg_opts)) { JS_FreeValue(ctx, arg_opts); arg_opts = JS_NULL; JS_FreeValue(ctx, JS_GetException(ctx)); }
    } else {
        arg_opts = JS_NULL;
    }
    JSValue argv[3] = { arg_src, arg_path, arg_opts };

    s->instr_count = 0;
    JSValue result = JS_Call(ctx, fn, JS_UNDEFINED, 3, argv);
    JS_FreeValue(ctx, argv[0]); JS_FreeValue(ctx, argv[1]); JS_FreeValue(ctx, argv[2]);
    JS_FreeValue(ctx, fn); JS_FreeValue(ctx, fe);

    if (JS_IsException(result)) {
        JS_FreeValue(ctx, result);
        /* Distinguish an interrupt (instruction-budget breach) from an ordinary throw. */
        const char *code = (s->instr_limit > 0 && s->instr_count > s->instr_limit)
                               ? "js.limit.instructions" : "js.internal";
        char *m = take_exception_message(ctx);
        int rc = fail_indeterminate(out_json, out_len, code, m);
        free(m);
        return rc;
    }

    /* Serialize the frontend-neutral facts. AST/session state never crosses here. */
    JSValue json = JS_JSONStringify(ctx, result, JS_UNDEFINED, JS_UNDEFINED);
    JS_FreeValue(ctx, result);
    if (JS_IsException(json)) {
        JS_FreeValue(ctx, json);
        char *m = take_exception_message(ctx);
        int rc = fail_indeterminate(out_json, out_len, "js.internal", m);
        free(m);
        return rc;
    }
    size_t jlen = 0;
    const char *js = JS_ToCStringLen(ctx, &jlen, json);
    if (!js) {
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.internal", "result is not serializable");
    }
    if (jlen > s->limits.max_result_bytes) {
        JS_FreeCString(ctx, js);
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.limit.result", "result exceeds max_result_bytes");
    }
    char *copy = malloc(jlen + 1);
    if (!copy) {
        JS_FreeCString(ctx, js);
        JS_FreeValue(ctx, json);
        return fail_indeterminate(out_json, out_len, "js.internal", "out of memory");
    }
    memcpy(copy, js, jlen);
    copy[jlen] = '\0';
    JS_FreeCString(ctx, js);
    JS_FreeValue(ctx, json);

    if (out_json) *out_json = copy; else free(copy);
    if (out_len) *out_len = jlen;
    return 0;
}
