/*
 * app_main.c - Generated by hull build
 *
 * Thin trampoline: provides main() which calls hl_app_run() from the linked
 * libhull_platform.a. hl_app_run is the slim app-runner entry (hull_serve
 * only) - it pulls none of the hull dev CLI (dispatch/subcommands/agent), so a
 * produced single-runtime app stays slim.
 */

extern int hl_app_run(int argc, char **argv);

int main(int argc, char **argv)
{
    return hl_app_run(argc, argv);
}
