/*
 * app_main.c — Generated by hull build
 *
 * Thin trampoline: provides main() which calls hull_main()
 * from the linked libhull_platform.a.
 */

extern int hull_main(int argc, char **argv);

int main(int argc, char **argv)
{
    return hull_main(argc, argv);
}
