/*
 * build_assets.c — Embedded platform library extraction
 *
 * Includes xxd-generated byte arrays for the platform .a and
 * template files. These are generated by the Makefile during
 * the two-stage build: compile → archive → xxd → embed.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#include "hull/build_assets.h"
#include <stdio.h>
#include <string.h>

/* These headers are generated by `make` — xxd of platform .a and templates */
#ifdef HL_BUILD_EMBEDDED
#include "embedded_platform.h"
#include "embedded_templates.h"
#endif

int hl_build_extract_platform(const char *dir)
{
#ifdef HL_BUILD_EMBEDDED
    if (!dir)
        return -1;

    char path[1024];
    snprintf(path, sizeof(path), "%s/libhull_platform.a", dir);

    FILE *f = fopen(path, "wb");
    if (!f)
        return -1;

    size_t written = fwrite(hl_embedded_platform_a,
                            1, hl_embedded_platform_a_len, f);
    fclose(f);

    return (written == hl_embedded_platform_a_len) ? 0 : -1;
#else
    (void)dir;
    fprintf(stderr, "hull build: platform library not embedded in this build\n");
    fprintf(stderr, "hint: rebuild hull with `make platform && make HL_BUILD_EMBEDDED=1`\n");
    return -1;
#endif
}

int hl_build_get_template(const char **data, size_t *len)
{
#ifdef HL_BUILD_EMBEDDED
    if (!data || !len)
        return -1;
    *data = (const char *)hl_embedded_app_main_c;
    *len = hl_embedded_app_main_c_len;
    return 0;
#else
    (void)data; (void)len;
    return -1;
#endif
}

int hl_build_get_entry_header(const char **data, size_t *len)
{
#ifdef HL_BUILD_EMBEDDED
    if (!data || !len)
        return -1;
    *data = (const char *)hl_embedded_entry_h;
    *len = hl_embedded_entry_h_len;
    return 0;
#else
    (void)data; (void)len;
    return -1;
#endif
}
